// Package shell knows how to integrate gouse with the user's interactive
// shell. Each supported shell implements the Shell interface and is
// registered in registry.go. Adding a new shell means creating one file
// with the implementation and one line in init() to register it.
package shell

// Shell is the contract every supported shell must fulfil.
//
// Implementations live in bash.go, zsh.go, fish.go. All filesystem paths
// are absolute and resolved against the current process's HOME.
type Shell interface {
	// Name is the canonical identifier ("bash", "zsh", "fish"). It's
	// used as the value for the --shell flag and to dispatch.
	Name() string

	// RCFile returns the file the user is expected to source the
	// integration script from (~/.bashrc, ~/.zshrc, ~/.config/fish/config.fish).
	RCFile() (string, error)

	// SourceLine is the literal line install.sh appends to RCFile.
	SourceLine() string

	// IntegrationPath returns where WriteIntegration writes
	// (~/.gouse/shell.sh, shell.zsh, shell.fish).
	IntegrationPath() (string, error)

	// WriteIntegration creates the integration script. Idempotent —
	// overwrites the existing file.
	WriteIntegration() (string, error)

	// CompletionFilename is the basename written next to the integration
	// script (completion.bash | completion.zsh | completion.fish). The
	// content is generated by Cobra in the cli layer.
	CompletionFilename() string

	// RenderEnv returns the script the function `gouse use <version>`
	// must eval to switch versions in the current shell. The output is
	// in the shell's own syntax (POSIX exports for bash/zsh, `set -gx`
	// for fish).
	RenderEnv(version string) (string, error)
}
